export const exampleBeers = [
  {
    submission_id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    user_id: "a481a908-737b-459e-9392-b5e100bda508",
    beername: "Golden Sunrise Lager",
    description:
      "A crisp and refreshing lager with subtle malt sweetness and a clean finish",
    brewer: "Sarah Johnson",
    style: "1A. American Lager Light",
    alcohol: 4.2,
    original_gravity: 11.8,
    ibu: 18,
    recipie_link: "https://brewingrecipes.com/golden-sunrise-lager",
  },
  {
    submission_id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
    user_id: "b592c019-848c-460f-a043-c6f201cea609",
    beername: "Hoppy Trail IPA",
    description:
      "Bold citrus and pine hop flavors with a strong bitter backbone and tropical fruit notes",
    brewer: "Mike Chen",
    style: "21A. American IPA",
    alcohol: 6.8,
    original_gravity: 16.2,
    ibu: 65,
    recipie_link: "https://ipamasters.com/hoppy-trail-recipe",
  },
  {
    submission_id: "6ba7b811-9dad-11d1-80b4-00c04fd430c8",
    user_id: "c703d130-959d-461g-b154-d7g312dfb720",
    beername: "Midnight Porter",
    description:
      "Rich chocolate and coffee notes with a smooth, velvety mouthfeel and roasted finish",
    brewer: "Emma Rodriguez",
    style: "20A. American Porter",
    alcohol: 5.4,
    original_gravity: 14.1,
    ibu: 28,
    recipie_link: "https://darkbeers.net/midnight-porter",
  },
  {
    submission_id: "7ca8c921-0ead-22e2-91c5-11d15fe541d9",
    user_id: "d814e241-a6ae-572h-c265-e8h423egc831",
    beername: "Wheat Field Hefeweizen",
    description:
      "Traditional German wheat beer with banana and clove esters, cloudy appearance",
    brewer: "Klaus Mueller",
    style: "10A. Weissbier",
    alcohol: 5.1,
    original_gravity: 12.9,
    ibu: 15,
    recipie_link: "https://germanbrewing.de/hefeweizen-classic",
  },
  {
    submission_id: "8db9d032-1fbe-33f3-a2d6-22e26gf652ea",
    user_id: "e925f352-b7bf-683i-d376-f9i534fhd942",
    beername: "Smoky Mountain Stout",
    description:
      "Imperial stout with notes of dark chocolate, espresso, and subtle smoke",
    brewer: "Jake Thompson",
    style: "20C. Imperial Stout",
    alcohol: 9.2,
    original_gravity: 22.4,
    ibu: 45,
    recipie_link: "https://stoutlovers.com/smoky-mountain-recipe",
  },
  {
    submission_id: "9eca0143-2gcf-44g4-b3e7-33f37hg763fb",
    user_id: "fa36g463-c8cg-794j-e487-gaj645gje053",
    beername: "Citrus Burst Pale Ale",
    description:
      "American pale ale featuring Citra and Mosaic hops with bright citrus character",
    brewer: "Lisa Park",
    style: "18B. American Pale Ale",
    alcohol: 5.6,
    original_gravity: 13.7,
    ibu: 42,
    recipie_link: "https://palealebrewing.com/citrus-burst",
  },
  {
    submission_id: "afdb1254-3hdf-55h5-c4f8-44g48ih874gc",
    user_id: "gb47h574-d9dh-8a5k-f598-hbk756hkf164",
    beername: "Belgian Abbey Dubbel",
    description:
      "Rich malty sweetness with dark fruit flavors and spicy Belgian yeast character",
    brewer: "Pierre Dubois",
    style: "26B. Belgian Dubbel",
    alcohol: 7.1,
    original_gravity: 17.8,
    ibu: 22,
    recipie_link: "https://belgianbrewing.be/abbey-dubbel-traditional",
  },
  {
    submission_id: "bfec2365-4ieg-66i6-d5g9-55h59ji985hd",
    user_id: "hc58i685-eaei-9b6l-g6a9-icl867ilg275",
    beername: "Farmhouse Saison",
    description:
      "Dry, spicy, and refreshing with peppery yeast character and light fruit notes",
    brewer: "Antoine Leblanc",
    style: "25B. Saison",
    alcohol: 6.3,
    original_gravity: 14.9,
    ibu: 30,
    recipie_link: "https://farmhouseales.fr/saison-classique",
  },
  {
    submission_id: "cgfd3476-5jfh-77j7-e6ha-66i6akj096ie",
    user_id: "id69j796-fbfj-ac7m-h7ba-jdm978jmh386",
    beername: "Oktoberfest Märzen",
    description:
      "Traditional German lager with rich malt character, amber color, and clean finish",
    brewer: "Hans Weber",
    style: "6A. Märzen",
    alcohol: 5.8,
    original_gravity: 14.6,
    ibu: 24,
    recipie_link: "https://oktoberfestbrewing.de/marzen-recipe",
  },
  {
    submission_id: "dhge4587-6kgi-88k8-f7ib-77j7blk1a7jf",
    user_id: "je7ak8a7-gcgk-bd8n-i8cb-kem089kni497",
    beername: "New England Hazy IPA",
    description:
      "Juicy and tropical with low bitterness, creamy mouthfeel, and intense hop aroma",
    brewer: "Tyler Brooks",
    style: "21B. Specialty IPA: New England IPA",
    alcohol: 6.5,
    original_gravity: 15.8,
    ibu: 35,
    recipie_link: "https://neipas.com/hazy-tropical-recipe",
  },
  {
    submission_id: "eihf5698-7lhj-99l9-g8jc-88k8cml2b8kg",
    user_id: "kf8bl9b8-hdhj-ce9o-j9dc-lfn19almj5a8",
    beername: "Bourbon Barrel Barleywine",
    description:
      "Rich and complex with caramel, vanilla, and oak notes from bourbon barrel aging",
    brewer: "Robert Martinez",
    style: "17D. English Barleywine",
    alcohol: 11.4,
    original_gravity: 26.7,
    ibu: 52,
    recipie_link: "https://barrelaged.com/bourbon-barleywine",
  },
  {
    submission_id: "fjig67a9-8mik-aalm-h9kd-99l9dnm3c9lh",
    user_id: "lg9cm0c9-ieik-df0p-kaed-mgoa2bmnk6b9",
    beername: "Pilsner Perfection",
    description:
      "Classic Czech-style pilsner with floral Saaz hops and crisp, clean malt backbone",
    brewer: "Václav Novák",
    style: "3A. Czech Pilsner",
    alcohol: 4.8,
    original_gravity: 12.2,
    ibu: 38,
    recipie_link: "https://czechpilsner.cz/traditional-recipe",
  },
  {
    submission_id: "gkjh78ba-9njl-bbmn-iake-aalmdno4dalm",
    user_id: "mhad1da-jfjl-eg1q-lbfe-nhpb3cnol7ca",
    beername: "Tropical Fruit Sour",
    description:
      "Tart and refreshing kettle sour with passion fruit, mango, and guava additions",
    brewer: "Jessica Wong",
    style: "23A. Berliner Weisse",
    alcohol: 4.1,
    original_gravity: 10.8,
    ibu: 8,
    recipie_link: "https://sourbeers.com/tropical-fruit-sour",
  },
  {
    submission_id: "hlki89cb-aokm-ccno-jblf-bbmneon5ebmn",
    user_id: "nibe2eb-kgkm-fh2r-mcgf-oiqc4dopm8db",
    beername: "Coffee Vanilla Porter",
    description:
      "Robust porter with cold-brew coffee and Madagascar vanilla bean additions",
    brewer: "David Kim",
    style: "20A. American Porter",
    alcohol: 5.9,
    original_gravity: 15.3,
    ibu: 32,
    recipie_link: "https://coffeebeers.net/vanilla-porter",
  },
  {
    submission_id: "imlj9adc-bpln-ddop-kcmg-ccnofoq6fcno",
    user_id: "ojcf3fc-lhlm-gi3s-ndhg-pjrd5epqn9ec",
    beername: "Highland Scottish Ale",
    description:
      "Malty Scottish ale with caramel sweetness and subtle peat smoke character",
    brewer: "Hamish MacLeod",
    style: "14B. Scottish Heavy",
    alcohol: 4.7,
    original_gravity: 12.8,
    ibu: 20,
    recipie_link: "https://scottishales.co.uk/highland-recipe",
  },
  {
    submission_id: "jnmk0bed-cqmo-eeqp-ldnh-ddopgpr7gdop",
    user_id: "pkdg4gd-mimn-hj4t-oeih-qkse6fqro0fd",
    beername: "Gose with Sea Salt",
    description:
      "Traditional German sour wheat beer with coriander and sea salt additions",
    brewer: "Ingrid Fischer",
    style: "23G. Gose",
    alcohol: 4.3,
    original_gravity: 11.4,
    ibu: 12,
    recipie_link: "https://gosebrewing.de/traditional-gose",
  },
  {
    submission_id: "konl1cfe-drno-ffqr-meoi-eeqphqs8heqp",
    user_id: "qleh5he-njno-ik5u-pfji-rlsf7grsp1ge",
    beername: "Double Chocolate Stout",
    description:
      "Decadent stout with cocoa nibs and dark chocolate, rich and creamy texture",
    brewer: "Maria Santos",
    style: "16D. Foreign Extra Stout",
    alcohol: 7.8,
    original_gravity: 18.9,
    ibu: 40,
    recipie_link: "https://chocolatestouts.com/double-chocolate",
  },
  {
    submission_id: "lpom2dgf-esop-ggrr-nfpj-ffqriqt9ifqr",
    user_id: "rmfi6if-okop-jl6v-qgkj-smtg8hstq2hf",
    beername: "Rye Whiskey Barrel Aged",
    description:
      "Bold rye beer aged in whiskey barrels with spicy rye character and oak notes",
    brewer: "Connor O'Brien",
    style: "31A. Alternative Grain Beer",
    alcohol: 8.6,
    original_gravity: 20.1,
    ibu: 48,
    recipie_link: "https://ryebeers.com/whiskey-barrel-aged",
  },
  {
    submission_id: "mqpn3ehg-ftpq-hhss-ogqk-ggrsjru0jgrs",
    user_id: "sngj7jg-plpq-km7w-rhll-tnuh9ituq3ig",
    beername: "Lavender Honey Wheat",
    description:
      "Light wheat beer with local wildflower honey and dried lavender flowers",
    brewer: "Sophie Laurent",
    style: "1D. American Wheat Beer",
    alcohol: 4.9,
    original_gravity: 12.6,
    ibu: 16,
    recipie_link: "https://floralbeers.fr/lavender-honey-wheat",
  },
];
